data:extend {{
  type = "double-setting",
  name = "fl-fire-size-multiplier",
  setting_type = "startup",
  default_value = 1.0,
  minimum_value = 0.0,
  maximum_value = 2.0,
  order = "a1",
}, {
  type = "double-setting",
  name = "fl-fire-spread-multiplier",
  setting_type = "startup",
  default_value = 1.2,
  minimum_value = 0.1,
  maximum_value = 5.0,
  order = "a2",
}, {
  type = "double-setting",
  name = "fl-expl-size-multiplier",
  setting_type = "startup",
  default_value = 1.0,
  minimum_value = 0.0,
  maximum_value = 2.0,
  order = "a3",
}, {
  type = "double-setting",
  name = "fl-nuke-effect-multiplier",
  setting_type = "startup",
  default_value = 1.0,
  minimum_value = 0.0,
  maximum_value = 3.0,
  order = "a4",
}, {
  type = "double-setting",
  name = "fl-proj-size-multiplier",
  setting_type = "startup",
  default_value = 1.0,
  minimum_value = 0.0,
  maximum_value = 2.0,
  order = "a4",
}, {
  type = "double-setting",
  name = "fl-flash-size-multiplier",
  setting_type = "startup",
  default_value = 1.0,
  minimum_value = 0.0,
  maximum_value = 2.0,
  order = "b1",
}, {type = "double-setting",
  name = "fl-silo-size-multiplier",
  setting_type = "startup",
  default_value = 1.0,
  minimum_value = 0.0,
  maximum_value = 2.0,
  order = "b2",
}, {
  type = "bool-setting",
  name = "fl-disable-unit-onmap",
  setting_type = "startup",
  default_value = true,
  order = "c1",
}, {
  type = "bool-setting",
  name = "fl-disable-segmented-unit-onmap",
  setting_type = "startup",
  default_value = false,
  order = "c2",
}, {
  type = "bool-setting",
  name = "fl-disable-night-minimap",
  setting_type = "startup",
  default_value = false,
  order = "d1",
}, {
  type = "bool-setting",
  name = "fl-disable-platform-minimap",
  setting_type = "startup",
  default_value = false,
  order = "d2",
}, {
  type = "bool-setting",
  name = "fl-nerf-nightvision",
  setting_type = "startup",
  default_value = false,
  order = "e1",
}, {
  type = "bool-setting",
  name = "fl-darker-nightvision",
  setting_type = "startup",
  default_value = false,
  order = "e2",
  hidden = true,
}, {
  type = "bool-setting",
  name = "fl-disable-hit-explosion",
  setting_type = "startup",
  default_value = false,
  order = "g",
}}
